/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import estructuras.Arbol_binario;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import proyecto2_edd.CargaMasiva;

/**
 *
 * @author Kelly
 */
public class VisualizarEstruturas extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarEstruturas
     */
    String id;
    
    public VisualizarEstruturas(String id) {
        this.id = id;
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

//Mostrar árbol Abl
    public void mostrarArbol_Avl(String id) {
        ImageIcon img = new ImageIcon( new ImageIcon("arbol_avl" + id + ".jpg").getImage());
        
        JLabel label = new JLabel();
        
        label.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
        
        label.setIcon(img);
        jScrollPane1.setViewportView(label);
    }
    
    public void mostrarArbol_binario(String id) {
        ImageIcon img = new ImageIcon("ArbolBi" + id + ".jpg");
        
        JLabel label = new JLabel();
        
        label.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
        
        label.setIcon(img);
        jScrollPane1.setViewportView(label);
    }
    
    public void mostrarArbol_Capa(String id, String nC) {
        ImageIcon img = new ImageIcon("Capa" + id + "_" + nC + ".jpg");
        
        JLabel label = new JLabel();
        
        label.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
        
        label.setIcon(img);
        jScrollPane1.setViewportView(label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver Arbol de Imagenes", "Ver Arbol de capas", "Ver listado de Albumes", "Ver capa" }));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(125, 125, 125)
                .addComponent(jButton2)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jComboBox1.getSelectedItem() == "Ver Arbol de Imagenes") {
            mostrarArbol_Avl(id);
        } else if (jComboBox1.getSelectedItem() == "Ver Arbol de capas") {
            mostrarArbol_binario(id);
        } else if (jComboBox1.getSelectedItem() == "Ver listado de Albumes") {
            
        } else if (jComboBox1.getSelectedItem() == "Ver capa") {
            
            String capa = JOptionPane.showInputDialog(null, "Ingrese el número de capa");
            CargaMasiva.arbol_b.bucar_binario(CargaMasiva.arbol_b.raiz, id);
            Arbol_binario arbolbi = CargaMasiva.arbol_b.arbol_bin;
            arbolbi.existeCapa = false;
            arbolbi.buscar_dato(arbolbi.raiz, Integer.parseInt(capa));
            if (arbolbi.existeCapa) {
                arbolbi.matriz.crearGrafo("Capa" + id + "_" + capa + ".jpg");
                mostrarArbol_Capa(id, capa);
                arbolbi.matriz = null;
                arbolbi.existeCapa = false;
            }
            
            CargaMasiva.arbol_b.arbol_bin = null;
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ventana_Usuario vU = new Ventana_Usuario(id);
        vU.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
